name: Post KNMI Pluimen naar Discord

on:
  workflow_dispatch:
  schedule:
    - cron: "15 7 * * *"   # 08:15 NL-tijd (wintertijd)
    - cron: "15 19 * * *"  # 20:15 NL-tijd (wintertijd)

jobs:
  send-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz discord.py

      - name: Run script
        env:
          DISCORD_PLUIMEN_BOT: ${{ secrets.DISCORD_PLUIMEN_BOT }}
          DISCORD_PLUIMEN_CHANNEL: ${{ secrets.DISCORD_PLUIMEN_CHANNEL }}
        run: python "Python code's/all_pluimen_to_discord.py"
